
drop table if exists certificate_tag;
drop table if exists gift_certificate;
drop table if exists tag;


create table gift_certificate(
    id int8 primary key generated by default as identity,
    name varchar not null ,
    description varchar,
    price decimal(15,2) not null,
    duration int8,
    create_date varchar not null,
    last_update_date varchar
                             );

create table tag (
    id int8 primary key generated by default as identity,
    name varchar not null
                 );

create table certificate_tag (
                certificate_id int8,
                tag_id int8,
                constraint pf_certificate_tag primary key (certificate_id, tag_id),
                constraint fk_certificate foreign key(certificate_id) references gift_certificate(id)
                on update cascade on delete cascade ,
                constraint fk_tag foreign key(tag_id) references tag(id) on delete cascade
                             );
